### PR TITLE
Add Search result

### LINKED ISSUE #2: Mock up UI for search page

### PR DESCRIPTION
**Pull request by victor-jr**
Closes #2 #6 and #9 
Added search results page. Will need to go to http://localhost:3000/#/job-search-results?title=Job%201 to test out the page.

### CODE REVIEW

**Comment by victor-jr** [comment]
@btwooton Hows this?

**Comment by btwooton** [comment]
@victor-jr looks good. Does this PR not also address issue #6 since you implemented the job card?

**Comment by victor-jr** [comment]
True. Fixed also including #9

**Comment by btwooton** [comment]
Looks good. Merging into master.

**Pull request merged**
